### ISSUE TITLE
next steps?

### ISSUE THREAD

**Issue by PierreRoos** [PierreRoos/Moodle-Scenario-Collaboration#2]
Does anybody have any ideas for what the next steps should be?

**Comment by razieh61** [comment]
I guess we need to learn Jenkins to build and deploy our python code without using pycharm through writing some scripts to automate these process.

**Comment by smjaye** [comment]
Pierre , I really don't know how to do it . I am still learning, cloning and all . Here my family is urging me to take supper. My daughter has just come from university.

**Comment by PierreRoos** [comment]
> Pierre , I really don't know how to do it . I am still learning, cloning and all . Here my family is urging me to take supper. My daughter has just come from university.

Hey, I didn't mean to add any pressure, its meant to be just for extra practice to try out GitHub if you want. Please go to your family! I hope you have a great weekend!

**Comment by PierreRoos** [comment]
I was thinking next steps in our code would be to add sign in with an admin account.
